title: Global Shapers Dublin Hub Black Lives Matter Pledge Wall
author: Anjukan Kathirgamanathan    
email: k.anjukan@gmail.com
description: >-
  This is the prototype for the pledge wall of the Global Shapers Dublin Hub Black Lives Matter Project.

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: globalshapersdublin
  linkedin: global-shapers-dublin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
